### PR TITLE
Cli: improve Next.js project detection

### LINKED ISSUE #260: [TRI-878] CLI init fails with Next.js projects that don't have a next.config.js
It's not compulsory to have a `next.config.js` file. For example this repo: [https://github.com/rishi-raj-jain/lemonsqueezy-nextjs-poc](https://github.com/rishi-raj-jain/lemonsqueezy-nextjs-poc).

Instead we should look at the `package.json` for the `next` dependency: [https://github.com/rishi-raj-jain/lemonsqueezy-nextjs-poc/blob/997ef6cd4680ee8bd4fe9d466ede6dacad3b0d91/package.json#L16](https://github.com/rishi-raj-jain/lemonsqueezy-nextjs-poc/blob/997ef6cd4680ee8bd4fe9d466ede6dacad3b0d91/package.json#L16)

This file needs updating with improved logic, checking for the `next` key in the package.json dependencies object. [https://github.com/triggerdotdev/trigger.dev/blob/main/packages/cli/src/utils/detectNextJsProject.ts](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/cli/src/utils/detectNextJsProject.ts)

It should be tested in a Next project – see the Contributions guide for how to test the CLI.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-878](https://linear.app/triggerdotdev/issue/TRI-878/cli-init-fails-with-nextjs-projects-that-dont-have-a-nextconfigjs)</sub>

### PR DESCRIPTION
**Pull request by matt-aitken**
## Problem

There isn't always a `next.config.js` file. 

## Solution
It's more reliable to look at the package.json dependencies object for a next key. 

Fixes #260

### CODE REVIEW

File: packages/cli/src/utils/detectNextJsProject.ts [hunk 1]
```diff
@@ -1,15 +1,17 @@
...
 /** Detects if the project is a Next.js project at path  */
 export async function detectNextJsProject(path: string): Promise<boolean> {
-  // Checks for the presence of a next.config.js file
+  // Checks for the presence of the next package in the package.json file
   try {
-    // Check if next.config.js file exists in the given path
-    await fs.access(pathModule.join(path, "next.config.js"));
-    return true;
+    const packageJsonPath = pathModule.join(path, "package.json");
+    const packageJsonContent = (await readJSONFile(packageJsonPath)) as PackageJson;
```
Comment (matt-aitken) [inline packages/cli/src/utils/detectNextJsProject.ts]: - [ ] Do `.catch()` locally.
- [ ] Move `readPackageJsonFile` to utils
- [ ] Check for next.config first, if it doesn't exist then do the package.json

**Review by ericallam — APPROVED** [review]
