### PR TITLE
fix: Added retry config and showed error from subtask in web

### LINKED ISSUE #422: Ensure `@trigger.dev/openai` background tasks have retry configuration
These backgroundFetch tasks need to have their retry configuration set:

- [`backgroundCreateCompletion`](https://github.com/triggerdotdev/trigger.dev/blob/4685b630d90f6b63db691759c15f2fd6aa433e80/integrations/openai/src/tasks.ts)
- [`backgroundCreateChatCompletion`](https://github.com/triggerdotdev/trigger.dev/blob/4685b630d90f6b63db691759c15f2fd6aa433e80/integrations/openai/src/tasks.ts)

View the docs on `backgroundFetch` retry here: https://trigger.dev/docs/sdk/io/backgroundfetch

And the OpenAI error codes here: https://platform.openai.com/docs/guides/error-codes

### PR DESCRIPTION
**Pull request by RamK777-stack**
fixes #422 and #159

Currently we are not showing the exact error on trigger.dev web If openAPI request failed. So I am trying to show the exact error and reason for the task failed.

My request failed because of insufficient quota, status code is 429. Unfortunately, both too many requests and insufficient quota are having same status code 429. This is with the background functions.

Previously it was 

image

Now I have fixed this like this

image (1)

Note: I didn't test positive flow. because currently, I don't have an active openAI key. I consumed all of my free quota

### CODE REVIEW

File: packages/trigger-sdk/src/io.ts [hunk 1]
```diff
@@ -527,7 +527,7 @@ export class IO {
         task,
       });
 
-      throw new Error(task.error ?? "Task errored");
+      throw new Error(task.error ?? JSON.stringify(task?.output));
```
Comment (matt-aitken) [inline packages/trigger-sdk/src/io.ts]: I think we still need the fallback "Task errored", if there's no task.output.

```suggestion
      throw new Error(task.error ?? task?.output ? JSON.stringify(task.output) : "Task errored");
```

**Review by matt-aitken — APPROVED** [review]
This is great! I made it so it falls back to "Task errored" if the task has no output
